
import React, {useEffect, useMemo, useState} from "react";
const ACCESS_CODE = "bernounews-2025";
const BRAND = { blue: "#273C8C", teal: "#11B6A3" };
const PAGES = { home:{path:"#",label:"Início"}, news:{path:"#noticias",label:"Notícias"}, forms:{path:"#formularios",label:"Formulários"}, quizzes:{path:"#quizzes",label:"Quizzes"}, suggest:{path:"#sugestoes",label:"Sugestões"}, about:{path:"#sobre",label:"Sobre"} };
function useHashRoute(){ const [h,setH]=useState(()=>window.location.hash||PAGES.home.path); useEffect(()=>{ const fn=()=>setH(window.location.hash||PAGES.home.path); addEventListener("hashchange",fn); return()=>removeEventListener("hashchange",fn)},[]); const p=Object.keys(PAGES).find(k=>PAGES[k].path===h)||"home"; return [p,(k)=> (window.location.hash=PAGES[k].path)]; }
function AdminToggle({isAdmin,setAdmin}){ return <button onClick={async()=>{ if(isAdmin){setAdmin(false);return;} const pw=prompt("Senha do modo Admin:"); const r=await fetch("/api/news/admin-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw||""})}); if(r.ok)setAdmin(true); else alert("Senha incorreta");}} className="ml-2 text-xs px-2 py-1 rounded-lg border">{isAdmin?"Sair do Admin":"Entrar (Admin)"}</button> }
function Shell({children,page,onNavigate,isAdmin,setAdmin}){ return (<div style={{"--brand-blue":BRAND.blue,"--brand-teal":BRAND.teal}} className="min-h-screen bg-[var(--brand-blue)]/5"><header className="sticky top-0 z-40 bg-white/90 border-b"><div className="max-w-6xl mx-auto px-4 py-3 flex items-center gap-3"><span className="text-2xl" style={{color:BRAND.teal}}>∞</span><div className="font-black text-xl md:text-2xl" style={{color:BRAND.blue}}>Bernou<span className="text-[var(--brand-teal)]">News</span></div><nav className="ml-auto flex gap-1">{Object.entries(PAGES).map(([k,v])=> <button key={k} onClick={()=>onNavigate(k)} className={`px-3 py-2 rounded-xl text-sm hover:bg-[var(--brand-teal)]/10 ${page===k?"bg-[var(--brand-teal)]/10":""}`}>{v.label}</button>)}</nav><AdminToggle isAdmin={isAdmin} setAdmin={setAdmin}/></div></header><main className="max-w-6xl mx-auto px-4 py-6">{children}</main><footer className="mt-10 border-t bg-white/80"><div className="max-w-6xl mx-auto px-4 py-6 text-sm flex flex-col md:flex-row gap-3 justify-between"><p>© {new Date().getFullYear()} BernouNews — Jornal da Sala.</p><p>Site criado por <strong>ChatGPT</strong> com as instruções da aluna <strong>Helena Fernandes</strong>.</p></div></footer></div>); }
function Hero(){ return (<section className="relative -mx-4 md:-mx-8 lg:-mx-16 xl:-mx-24 2xl:-mx-36"><div className="relative"><img src="/bcmf-arquitetos-bernoulli-cidade-jardim-primary-schools-archello.1747848970.5926.jpg" alt="Prédio do Bernoulli" className="w-full h-[52vh] md:h-[68vh] object-cover"/><div className="absolute inset-0" style={{background:"linear-gradient(180deg,rgba(0,0,0,.35),rgba(0,0,0,.2) 40%,rgba(0,0,0,.55))"}}/><div className="absolute inset-0 grid place-items-center px-4"><div className="text-center text-white drop-shadow-lg"><h1 className="text-4xl md:text-6xl font-black">BernouNews</h1><p className="mt-3 text-base md:text-lg text-white/90 max-w-3xl mx-auto">O jornal colaborativo da nossa turma — notícias, opiniões, enquetes e quizzes.</p><div className="mt-6 flex flex-col sm:flex-row gap-3 justify-center"><a href={PAGES.news.path} className="px-6 py-3 rounded-2xl font-semibold text-white" style={{background:BRAND.teal}}>Ver notícias</a><a href={PAGES.forms.path} className="px-6 py-3 rounded-2xl font-semibold border border-white/70 text-white/95">Votar / Responder</a></div></div></div></div></section>); }
function Home(){ return (<><Hero/><section className="mt-10 grid md:grid-cols-3 gap-6">{[{title:"Escreva sua primeira notícia",href:PAGES.news.path,desc:"Ative o modo Admin e publique!",icon:"📝"},{title:"Crie uma enquete",href:PAGES.forms.path,desc:"Pergunte e veja resultados ao vivo.",icon:"📊"},{title:"Monte um quiz",href:PAGES.quizzes.path,desc:"Desafie seus colegas.",icon:"🧠"}].map((c,i)=>(<a key={i} href={c.href} className="block rounded-2xl p-4 bg-white border shadow-sm hover:shadow-md"><div className="text-3xl">{c.icon}</div><h3 className="mt-2 font-semibold" style={{color:BRAND.blue}}>{c.title}</h3><p className="text-slate-700">{c.desc}</p></a>))}</section></>); }
function useNews(){ const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); useEffect(()=>{(async()=>{ try{ const r=await fetch("/api/news"); const d=await r.json(); setItems(d.items||[]);}catch(e){setError("Falha ao carregar notícias");}finally{setLoading(false);} })();},[]); return {items,setItems,loading,error}; }
async function serverCreate(post){ const r=await fetch("/api/news",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(post)}); if(!r.ok) throw new Error("Erro ao criar"); return await r.json(); }
async function serverUpdate(id,patch){ const r=await fetch("/api/news/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}); if(!r.ok) throw new Error("Erro ao editar"); return await r.json(); }
async function serverDelete(id){ const r=await fetch("/api/news/"+id,{method:"DELETE"}); if(!r.ok) throw new Error("Erro ao deletar"); return await r.json(); }
function NewPostButton({onCreate}){ return <button onClick={async()=>{ const title=prompt("Título da notícia:")?.trim(); if(!title) return; const author=prompt("Autor(a):","Redação BernouNews")?.trim()||"Redação BernouNews"; const tags=(prompt("Tags (vírgulas):","geral")||"").split(",").map(s=>s.trim()).filter(Boolean); const body=window.prompt("Texto da notícia:")||""; const images=(prompt("Imagens (URLs separadas por vírgula):","")||"").split(",").map(s=>s.trim()).filter(Boolean); const created=await serverCreate({title,author,tags,body,images,date:new Date().toISOString().slice(0,10)}); onCreate(created.item);} } className="px-3 py-2 rounded-xl text-white font-medium" style={{background:BRAND.teal}}>Nova notícia</button> }
function PostCard({post,isAdmin,onChange,onDelete}){ const cover=post.images?.[0]||null; const go=()=>{ window.location.hash="#noticia-"+post.id; }; const edit=async()=>{ const title=prompt("Título:",post.title)||post.title; const author=prompt("Autor(a):",post.author||"Redação BernouNews")||post.author; const tags=(prompt("Tags:",(post.tags||[]).join(", "))||"").split(",").map(s=>s.trim()).filter(Boolean); const body=window.prompt("Texto:",post.body||"")||post.body; const images=(prompt("Imagens (URLs):",(post.images||[]).join(", "))||"").split(",").map(s=>s.trim()).filter(Boolean); const saved=await serverUpdate(post.id,{title,author,tags,body,images}); onChange(saved.item); }; const del=async()=>{ if(!confirm("Apagar esta notícia?")) return; await serverDelete(post.id); onDelete(post.id); }; return (<article className="rounded-2xl overflow-hidden bg-white border shadow-sm">{cover?<img src={cover} alt="Capa" className="w-full h-48 object-cover"/>:<div className="w-full h-48 bg-gradient-to-r from-[var(--brand-teal)] to-[var(--brand-blue)]"/>}<div className="p-4"><h3 className="text-lg font-bold" style={{color:BRAND.blue}}>{post.title}</h3><p className="mt-1 text-sm text-slate-600">Por {post.author} • {new Date(post.date).toLocaleDateString()}</p><p className="mt-3 line-clamp-3 text-slate-700 whitespace-pre-wrap">{post.body}</p><div className="mt-3 flex items-center justify-between"><div className="flex gap-2 flex-wrap">{(post.tags||[]).map(t=><span key={t} className="text-xs px-2 py-1 rounded-full bg-[var(--brand-teal)]/10">#{t}</span>)}</div><div className="flex items-center gap-2"><button onClick={go} className="text-sm font-semibold" style={{color:BRAND.teal}}>Ler »</button>{isAdmin&&<button onClick={edit} className="text-xs px-2 py-1 rounded border">Editar</button>}{isAdmin&&<button onClick={del} className="text-xs px-2 py-1 rounded border">Excluir</button>}</div></div></div></article>); }
function SinglePost(){ const [post,setPost]=useState(null); const [err,setErr]=useState(""); useEffect(()=>{ const id=window.location.hash.replace("#noticia-",""); (async()=>{ try{ const r=await fetch("/api/news/"+id); const d=await r.json(); setPost(d.item||null);}catch(e){setErr("Falha ao carregar.")} })(); },[]); if(err) return <p className="text-red-600">{err}</p>; if(!post) return <p>Carregando…</p>; return (<article className="prose max-w-none"><button onClick={()=>window.location.hash=PAGES.news.path} className="mb-4 text-sm" style={{color:BRAND.teal}}>← Voltar</button><h1 className="mb-0" style={{color:BRAND.blue}}>{post.title}</h1><p className="mt-1 text-slate-600">Por {post.author} • {new Date(post.date).toLocaleDateString()}</p>{post.images?.length>0&&<div className="grid md:grid-cols-2 gap-3 my-4">{post.images.map((src,i)=>(<img alt={`imagem ${i+1}`} key={i} src={src} className="rounded-xl border"/>))}</div>}<div className="text-slate-800 whitespace-pre-wrap">{post.body}</div><div className="mt-4"><a href={PAGES.news.path} className="px-3 py-2 rounded-xl font-semibold border" style={{borderColor:BRAND.teal,color:BRAND.blue}}>Mais notícias</a></div></article>); }
function FormsPage(){ return (<section><h2 className="text-2xl font-bold" style={{color:BRAND.blue}}>Formulários & Enquetes</h2><p className="text-slate-600 mt-2">Em breve: enquetes e formulários.</p></section>); }
function QuizzesPage(){ return (<section><h2 className="text-2xl font-bold" style={{color:BRAND.blue}}>Quizzes</h2><p className="text-slate-600 mt-2">Em breve: quizzes da turma.</p></section>); }
function SuggestPage(){ return (<section><h2 className="text-2xl font-bold" style={{color:BRAND.blue}}>Sugestões</h2><p className="text-slate-600 mt-2">Envie ideias de matérias para o jornal.</p></section>); }
function AboutPage(){ return (<section className="prose max-w-none"><h2 style={{color:BRAND.blue}}>Sobre o BernouNews</h2><p>Site criado por <em>ChatGPT</em> com as instruções da aluna <strong>Helena Fernandes</strong>.</p></section>); }
function AccessGate({children}){ const [ok,setOk]=useState(()=>{ const u=new URL(window.location.href); if(u.searchParams.get("key")===ACCESS_CODE){ localStorage.setItem("bn.access","1"); return true;} return localStorage.getItem("bn.access")==="1"; }); const [code,setCode]=useState(""); if(ok) return children; return (<div className="min-h-screen grid place-items-center bg-[var(--brand-blue)]/10"><div className="p-6 rounded-2xl bg-white border max-w-sm text-center"><h1 className="text-2xl font-bold" style={{color:BRAND.blue}}>Acesso restrito</h1><p className="mt-2 text-slate-700">Digite o código de acesso para entrar.</p><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Código" className="mt-4 w-full px-3 py-2 border rounded-xl"/><button onClick={()=>{ if(code===ACCESS_CODE){ localStorage.setItem("bn.access","1"); setOk(true);} else alert("Código inválido"); }} className="mt-3 w-full px-3 py-2 rounded-xl text-white" style={{background:BRAND.teal}}>Entrar</button></div></div>); }
export default function App(){ const [page,navigate]=useHashRoute(); const [isAdmin,setAdmin]=useState(false); useEffect(()=>{ document.title="BernouNews"; },[]); useEffect(()=>{ document.documentElement.style.setProperty('--brand-blue',BRAND.blue); document.documentElement.style.setProperty('--brand-teal',BRAND.teal); },[]); if(typeof window!=='undefined' && window.location.hash.startsWith("#noticia-")){ return (<AccessGate><Shell page="news" onNavigate={navigate} isAdmin={isAdmin} setAdmin={setAdmin}><SinglePost/></Shell></AccessGate>); } return (<AccessGate><Shell page={page} onNavigate={navigate} isAdmin={isAdmin} setAdmin={setAdmin}>{page==="home"&&<Home/>}{page==="news"&&<NewsPage isAdmin={isAdmin}/>} {page==="forms"&&<FormsPage/>}{page==="quizzes"&&<QuizzesPage/>}{page==="suggest"&&<SuggestPage/>}{page==="about"&&<AboutPage/>}</Shell></AccessGate>); }
